apiUrl: http://localhost:9001
reportUrl: http://reports.coulsdon.ac.uk/ReportServer
studentImagesUrl: http://student-imgs.coulsdon.ac.uk
debug: true
profile: dev
location: cc

#resourceLocation: /resources/dist/