app:
  name: cis-template

#server:
#  port: 10201

security:
  sessions: NEVER

spring:
#  profiles:
#    active: dev
#  pidfile: ${app.name}.pid

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
      
beanlogger: 
  enabled: false
